### ISSUE TITLE
Food image randomanization

### ISSUE THREAD

**Issue by elvandy** [jefferythewind/appetite_tamer#9]
Hi Tim, can you please check whether the food image is divided into 17 sets and users only get one set per day? Also, can you please check whether the whole image set will be reshuffled every 17 days? Thanks

**Comment by jefferythewind** [comment]
Hi Andy it looks like there definitely are 17 sets, but I will have to look more into it to be sure how the images are arranged for the games.  I will get back to you.

**Comment by richlopez41** [comment]
Yes, I had the same question and had chatted with Andy about ityesterday..this morning I noticed the images were the same as the ones from other days earlier this week (all after I had pushed the latest update).

**Comment by jefferythewind** [comment]
Great feedback, guys.  We will definitely get to the bottom of this.

**Comment by jefferythewind** [comment]
This should be fixed in Version 1 Build 5
